

Expression ::= PlusExpression;

PlusExpression ::= MultiplyExpression "+" PlusExpression, MultiplyExpression "-" PlusExpression, MultiplyExpression;

MultiplyExpression ::= SimpleExpression "*" MultiplyExpression, SimpleExpression "/" MultiplyExpression, 
    SimpleExpression;

SimpleExpression ::= "(" Expression ")", VariableExpression, NumberExpression;