#ifndef RANDOM_OBMAM784PLIKUCNSZSBE91KGI23L8IK0TMSPWJ0IJIAICZBUMMKOBWRSMMA
#define RANDOM_OBMAM784PLIKUCNSZSBE91KGI23L8IK0TMSPWJ0IJIAICZBUMMKOBWRSMMA

#include <string>

namespace vegetable_script {

struct DoubleException {
  std::string status;
};

}

#endif  // RANDOM_OBMAM784PLIKUCNSZSBE91KGI23L8IK0TMSPWJ0IJIAICZBUMMKOBWRSMMA
